# Generated by Django 5.0.6 on 2024-06-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_producto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='tipo',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('administrador', 'Administrar')], default='usuario', max_length=100),
        ),
    ]
