# Generated by Django 5.0.6 on 2024-06-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_roles_tipo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='django_producto',
        ),
    ]
