# Generated by Django 5.0.6 on 2024-06-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_producto_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table=None,
        ),
    ]
