# Generated by Django 5.0.6 on 2024-06-21 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_solicitudintercambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudintercambio',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to='API.usuario'),
        ),
        migrations.AlterField(
            model_name='solicitudintercambio',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to='API.usuario'),
        ),
    ]
