# Generated by Django 5.0.6 on 2024-06-27 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_solicitudintercambio_propietario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.carrera'),
        ),
    ]
