# Generated by Django 5.0.6 on 2024-06-30 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_remove_usuario_last_login_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_admin',
        ),
    ]
