# Generated by Django 5.0.6 on 2024-07-01 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_remove_usuario_groups_remove_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.roles'),
            preserve_default=False,
        ),
    ]
